### ISSUE TITLE
Centroid of each parcellation

### ISSUE THREAD

**Issue by bgunasekera** [DiedrichsenLab/cerebellar_atlases#5]
Hi,

Apologies if this is trivial. 

I am trying to determine the centroid MNI coordinate of each parcellation of Diedrichsen_2009 atl-Anatom_desc-confid_space-MNI.nii

For example, Left_I_IV [X , Y, Z] 

Are there any ideas on how best to do this?

Best wishes,
Brandon

**Comment by jdiedrichsen** [comment]
There is no automatic way of doing this - but it's pretty straightforward. Do you need example code in Matlab (using SPM) or Python (using nibabel)?

**Comment by Zhongyuke** [comment]
yes! truly thank you !



---Original---
From: "Jorn ***@***.***&gt;
Date: Tue, Sep 14, 2021 00:45 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [DiedrichsenLab/cerebellar_atlases] Centroid of each parcellation (#5)




 
There is no automatic way of doing this - but it's pretty straightforward. Do you need example code in Matlab (using SPM) or Python (using nibabel)?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
